### PR TITLE
Use ProcessPoolExecutor for multiprocessing and fix logging

### PR DESCRIPTION
**Pull request by nemith**
This switches to using a ProcessPoolExecutor which is a bit cleaner way
of handling a multiprocessing pool and also allows for RenderFile and
RenderACL to return it's results instead of appending to an existing
thread-safe list which is much more straight forward.

In addition logging was only being setup on the main process.  This
calls a setup_logging() function at the start of each multiprocessing
function to make sure all logging is done for all subprocesses (which
should make it match when multiprocessing isn't used).

This will allow a future (already written) PR to remove absl logging in
favor for the standar library `logging function`

### CODE REVIEW

**Comment by ankenyr** [comment]
@all-contributors, let's add @nemith for code contributions.

**Comment by ankenyr** [comment]
@all-contributors please add @nemith for code

**Comment by ankenyr** [comment]
Hi Brandon, we saw this is still in draft still. Were you still working on things here?

**Comment by ankenyr** [comment]
Hey @nemith just checking in again. Is this expected to be a draft or are you looking for a review?

**Comment by nemith** [comment]
This is still a draft.  I was going to fix logging first, but it's already pretty broken.

**Pull request closed without merging**
